#!/bin/bash
# ref: https://docs.docker.com/docker-cloud/builds/advanced/

if [ "$DOCKER_TAG" == "latest" ] ; then echo 'No need to tag latest, exit.'; exit 0; fi

docker tag $IMAGE_NAME $DOCKER_REPO:latest
docker push $DOCKER_REPO:latest
