#!/bin/bash
# ref: https://docs.docker.com/docker-cloud/builds/advanced/

BASE_IMAGE_TAG=alpine

[[ "$DOCKER_TAG" != "latest" ]] && BASE_IMAGE_TAG=${DOCKER_TAG}-${BASE_IMAGE_TAG}

docker build \
    --build-arg BASE_IMAGE_TAG=${BASE_IMAGE_TAG} \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME .
