#!/bin/bash
# ref: https://docs.docker.com/docker-cloud/builds/advanced/

IMAGE_TAG=alpine

[[ "$DOCKER_TAG" != "latest" ]] && IMAGE_TAG=${DOCKER_TAG}-${IMAGE_TAG}

docker build \
    --build-arg IMAGE_TAG=${IMAGE_TAG} \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME .
