#!/bin/bash
# ref: https://docs.docker.com/docker-hub/builds/advanced/

BASE_IMAGE_TAG=fpm-alpine
VERSION=${DOCKER_TAG%%-*}

[[ "$DOCKER_TAG" != "latest" ]] && BASE_IMAGE_TAG=${VERSION}-${BASE_IMAGE_TAG}

docker build \
    --build-arg BASE_IMAGE_TAG=${BASE_IMAGE_TAG} \
    --build-arg DOCKER_TAG=${DOCKER_TAG} \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME .
