#!/bin/bash
# ref: https://docs.docker.com/docker-hub/builds/advanced/

[[ ! "$DOCKER_TAG" =~ ^[0-9.]+$ ]] && echo 'No need to tag latest, exit.' && exit

docker tag $IMAGE_NAME $DOCKER_REPO:latest
docker push $DOCKER_REPO:latest
