name: Auto Tag

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: run
        name: Run
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
