name: Build and push image

on:
  push:
    tags:
      - '*-*'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Version
        run: |
          version=${GITHUB_REF##*-}
          base_image_tag=${version}-alpine
          echo "VERSION=${version}" >> $GITHUB_ENV
          echo "BASE_IMAGE_TAG=${base_image_tag}" >> $GITHUB_ENV

      - name: '[nginx] Build and push'
        if: ${{ contains(github.ref, 'nginx') && success() }}
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          push: true
          platforms: |
            linux/amd64
            linux/arm64/v8
            linux/arm/v7
          build-args: |
            BASE_IMAGE_TAG=${{ env.BASE_IMAGE_TAG }}
          tags: |
            choyri/nginx:${{ env.VERSION }}
            choyri/nginx:latest
